TabloidMVC/Models/Post.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TabloidMVC.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [DisplayName("Header Image URL")]
        public string ImageLocation { get; set; }

        public DateTime CreateDateTime { get; set; }

        [DisplayName("Published")]
        [DataType(DataType.Date)]
        public DateTime? PublishDateTime { get; set; }

        public bool IsApproved { get; set; }

        [Required]
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        [DisplayName("Author")]
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }

        [DisplayName("Tags")]
        public string Tag { get; set; }
        public Tag tag { get; set; }

        public bool DELETED { get; set; }
    }
}

TabloidMVC/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentRepository _commentRepo;
        private readonly IPostRepository _postRepository;

        public CommentsController(ICommentRepository commentRepository, IPostRepository postRepository)
        {
            _commentRepo = commentRepository;
            _postRepository = postRepository;
        }





        // GET: CommentsController
        public ActionResult Index(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);
            List<Comment> comments = _commentRepo.GetAllCommentsByPost(id);
            PostCommentsViewModel vm = new PostCommentsViewModel()
            {
                Post = post,
                Comments = comments
            };
            return View(vm);
        }

        // GET: CommentsController/Details/5
        public ActionResult Details(int id)
        {
            var comment = _commentRepo.GetCommentById(id);
            if (comment == null)
            {
                comment = _commentRepo.GetCommentById(id);
                if (comment == null)
                {
                    return NotFound();
                }
            }
            return View(comment);
        }





        // GET: CommentsController/Create
        public ActionResult Create()
        {
            return View();
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Comment comment)
        {
            try
            {
                comment.UserProfileId = GetCurrentUserId();
                DateTime dt = DateTime.Now;
                comment.CreateDateTime = dt;
                _commentRepo.AddComment(comment);
                        

                return RedirectToAction("Index", new { id = comment.PostId });
            }  
            catch (Exception ex)
            {
                return View(comment);
            }
        }




        // GET: CommentsController/Edit/5
        public ActionResult Edit(int id)
        {
            Comment comment = _commentRepo.GetCommentById(id);
            int userId = GetCurrentUserId();


            if (comment == null)
            {
                return NotFound();
            }
            else
            {
                if (comment.UserProfileId == userId)
                {
                    return View(comment);
                }
                else
                {
                    return NotFound();
                }
            }

        }

        // POST: CommentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Comment comment)
        {
            comment.Id = id;
            try
            {
                _commentRepo.EditComment(comment);
                return RedirectToAction("Index", new { id = comment.PostId });
            }
            catch (Exception ex)
            {
                return View(comment);
            }
        }





        // GET: CommentsController/Delete/5
        [Authorize]
        public ActionResult Delete(int id) 
        {
            Comment comment = _commentRepo.GetCommentById(id);

            int userId = GetCurrentUserId();
            if (comment.UserProfileId == userId)
            {
                return View(comment);
            }
            else
            {
                return NotFound();
            }
        }

        // POST: CommentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Comment comment)
        {
            var databaseComment = _commentRepo.GetCommentById(id);

            try
            {
                _commentRepo.DeleteComment(id);

                return RedirectToAction("Index", new { id = databaseComment.PostId });
            }
            catch (Exception ex)
            {
                return View(comment);
            }
        }





        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

TabloidMVC/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualBasic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TabloidMVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITagRepository _tagRepository;

        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, ITagRepository tagRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _tagRepository = tagRepository;
        }

        public IActionResult Index()
        {
            List<Post> posts = _postRepository.GetAllPublishedPosts();
            List<Tag> tags = _tagRepository.GetTagsByPostId();
            PostIndexViewModel vm = new PostIndexViewModel()
            {
                Posts = posts,
                Tags = tags
            };
            
            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var post = _postRepository.GetPublishedPostById(id);

            List<Post> PostWithTags = _postRepository.GetTagByPostId(id);

            

            if (post == null)
            {
                int userId = GetCurrentUserProfileId();
                post = _postRepository.GetUserPostById(id, userId);
                if (post == null)
                {
                    return NotFound();
                }
            }
           
            PostDetailsViewModel vm = new PostDetailsViewModel()
            {
                Post = post,
                TagsByPostId = PostWithTags,
                
            };
            return View(vm);
        }

        public IActionResult Create()
        {
            var vm = new PostCreateViewModel();
            var AllTags = _tagRepository.GetAllTags();
            vm.Tags = new List<SelectListItem>();
            foreach (Tag tag in AllTags)
            {
                SelectListItem tagOption = new SelectListItem()
                {
                    Value = tag.Id.ToString(),
                    Text = tag.Name
                };
                vm.Tags.Add(tagOption);
            }

            vm.CategoryOptions = _categoryRepository.GetAll();
                       
            
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel vm)
        {
            try
            {
                vm.Post.CreateDateTime = DateAndTime.Now;
                vm.Post.IsApproved = true;
                vm.Post.UserProfileId = GetCurrentUserProfileId();
                vm.Post.DELETED = false;
                
                _postRepository.Add(vm.Post);

                foreach(var tagId in vm.SelectedTags)
                {
                    _postRepository.InsertTag(vm.Post.Id, tagId);
                }
                
                return RedirectToAction("Details", new { id = vm.Post.Id });
            } 
            catch
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        [Authorize]
        public IActionResult Edit(int id)
        {

            int currentUserId = GetCurrentUserProfileId();
            Post post = _postRepository.GetUserPostById(id, currentUserId);
            List<Category> categories = _categoryRepository.GetAll();
            List<Tag> tags = _tagRepository.GetAllTags();
            
            PostEditViewModel vm = new PostEditViewModel()
            {
                Post = post,
                CategoryOptions = categories,
                Tags = tags,
                Tag = new Tag()
            };

            if(post == null)
            {
                return NotFound();
            }

            if(post.UserProfileId == currentUserId)
            {
                return View(vm);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Post post)
        {
            try
            {
                int currentUserId = GetCurrentUserProfileId();
                Post originalPost = _postRepository.GetUserPostById(id, currentUserId);
                
                post.Id = id;
                post.CreateDateTime = originalPost.CreateDateTime;
                // Setting this to always be true for easy testing, may need to set this to false later so an admin can approve edits
                post.IsApproved = true;
                post.PublishDateTime = originalPost.PublishDateTime;
                post.UserProfileId = currentUserId;

                _postRepository.UpdatePost(post);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                List<Category> categories = _categoryRepository.GetAll();
                List<Tag> tags = _tagRepository.GetAllTags();
                PostEditViewModel vm = new PostEditViewModel()
                {
                    Post = post,
                    CategoryOptions = categories,
                    Tags = tags,
                    Tag = new Tag()
                };
                return View(vm);
            }
        }

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }



        [Authorize]
        public ActionResult Delete(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);
            int userId = GetCurrentUserId();

            if (post.UserProfileId == userId)
            {
                return View(post);
            }
            else
            {
                return NotFound();
            }
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Post post)
        {
            try
            {
                _postRepository.DeletePost(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(post);
            }
        }


        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }

       
    }
}

TabloidMVC/Views/Post/Create.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Create";
}



<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">What do you have to say?</h3>
            <form class="mt-5 card-body" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.PublishDateTime" class="control-label"></label>
                    <input asp-for="Post.PublishDateTime" class="form-control" />
                    <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control">
                        @foreach (var category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <select asp-for="@Model.SelectedTags" class="form-control" multiple asp-items="Model.Tags"> </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Delete.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsApproved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserProfileId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserProfileId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TabloidMVC/Views/Post/Details.cshtml
@model TabloidMVC.Models.ViewModels.PostDetailsViewModel

@{
    ViewData["Title"] = $"Post - {Model.Post.Title}";
}

<div class="container pt-5">
    <div class="post">
        <section class="px-3">
            <div class="row justify-content-between">
                <h1 class="text-secondary">@Model.Post.Title</h1>
                <h1 class="text-black-50">@Model.Post.Category.Name</h1>
            </div>
            <div class="row justify-content-between">
                <p class="text-secondary">Written by @Model.Post.UserProfile.DisplayName</p>
                <p class="text-black-50">Published on @Html.DisplayFor(model => model.Post.PublishDateTime)</p>
            </div>
            <div class="row justify-content-between">
                <p class="text-secondary">  @foreach (var tag in Model.TagsByPostId)
                {
                    @Html.DisplayFor(modelItem => tag.tag.Name)
                }</p>
            </div>
            <div class="row">
                <a asp-action="Edit" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Edit">
                    <i class="fas fa-pencil-alt"></i>
                </a>

                <a asp-action="Delete" asp-route-id="@Model.Post.Id" class="btn btn-outline-primary mx-1" title="Delete">

                <a asp-controller="Comments" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Comments">
                    <i class="far fa-comments"></i>
                </a>
                <a asp-controller="Comments" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Add Comment">
                    <i class="far fa-plus-square"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Delete">

                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </section>
        <hr />
        @if (!string.IsNullOrWhiteSpace(Model.Post.ImageLocation))
        {
            <section class="row justify-content-center">
                <div>
                    <img src="@Model.Post.ImageLocation" />
                </div>
            </section>
        }
        <section class="row post__content">
            <p class="col-sm-12 mt-5">@Html.DisplayFor(model => model.Post.Content)</p>
        </section>
    </div>
</div>

TabloidMVC/Views/Post/Edit.cshtml
@model TabloidMVC.Models.ViewModels.PostEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">What would you like to edit?</h3>
            <form class="mt-5 card-body" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control">
                        <option value="">Select Neighborhood</option>
                        @foreach (Category category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
}
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Tag" class="control-label"></label>
                    <select asp-for="Post.Tag" class="form-control">
                        <option value="">Select Tag</option>
                        @foreach (var tag in Model.Tags)
                        {
                            <option value="@tag.Id">@tag.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.Tag" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <button asp-action="Index" value="Cancel" class="btn btn-primary">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

TabloidMVC/Views/Post/Index.cshtml
@model TabloidMVC.Models.ViewModels.PostIndexViewModel

@{
    ViewData["Title"] = "Index";
}


<div class="container pt-5">
    <h1>Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.post.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.post.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.post.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.post.PublishDateTime)
                </th>
                <th>
                    Tags
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model.Posts)
            {
            <tr>
                @if (post.DELETED != true)
                {
                <td>
                    @Html.DisplayFor(modelItem => post.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => post.UserProfile.DisplayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => post.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => post.PublishDateTime)
                </td>
                }
                @foreach (var tag in Model.Tags)
                {
                    if (tag.PostId == post.Id)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => tag.Name)
                        </td>
                    }

                }
                <td>
                    <a asp-action="Details" asp-route-id="@post.Id" class="btn btn-outline-primary mx-1" title="View">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a asp-action="Edit" asp-route-id="@post.Id" class="btn btn-outline-primary mx-1" title="Edit">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                    <a asp-action="Delete" asp-route-id="@post.Id" class="btn btn-outline-primary mx-1" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>