TabloidMVC/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace TabloidMVC.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public int UserProfileId { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Content { get; set; }
        public DateTime CreateDateTime { get; set; }
        public UserProfile Author { get; set; }
    }
}

TabloidMVC/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentRepository _commentRepo;
        private readonly IPostRepository _postRepository;

        public CommentsController(ICommentRepository commentRepository, IPostRepository postRepository)
        {
            _commentRepo = commentRepository;
            _postRepository = postRepository;
        }





        // GET: CommentsController
        public ActionResult Index(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);
            List<Comment> comments = _commentRepo.GetAllCommentsByPost(id);
            PostCommentsViewModel vm = new PostCommentsViewModel()
            {
                Post = post,
                Comments = comments
            };
            return View(vm);
        }

        // GET: CommentsController/Details/5
        public ActionResult Details(int id)
        {
            var comment = _commentRepo.GetCommentById(id);
            if (comment == null)
            {
                comment = _commentRepo.GetCommentById(id);
                if (comment == null)
                {
                    return NotFound();
                }
            }
            return View(comment);
        }





        // GET: CommentsController/Create
        public ActionResult Create()
        {
            return View();
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Comment comment)
        {
            try
            {
                comment.UserProfileId = GetCurrentUserId();
                DateTime dt = DateTime.Now;
                comment.CreateDateTime = dt;
                _commentRepo.AddComment(comment);
                        

                return RedirectToAction("Index", new { id = comment.PostId });
            }  
            catch (Exception ex)
            {
                return View(comment);
            }
        }




        // GET: CommentsController/Edit/5
        public ActionResult Edit(int id)
        {
            Comment comment = _commentRepo.GetCommentById(id);
            int userId = GetCurrentUserId();


            if (comment == null)
            {
                return NotFound();
            }
            else
            {
                if (comment.UserProfileId == userId)
                {
                    return View(comment);
                }
                else
                {
                    return NotFound();
                }
            }

        }

        // POST: CommentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Comment comment)
        {
            comment.Id = id;
            try
            {
                _commentRepo.EditComment(comment);
                return RedirectToAction("Index", new { id = comment.PostId });
            }
            catch (Exception ex)
            {
                return View(comment);
            }
        }





        // GET: CommentsController/Delete/5
        [Authorize]
        public ActionResult Delete(int id) 
        {
            Comment comment = _commentRepo.GetCommentById(id);

            int userId = GetCurrentUserId();
            if (comment.UserProfileId == userId)
            {
                return View(comment);
            }
            else
            {
                return NotFound();
            }
        }

        // POST: CommentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Comment comment)
        {
            var databaseComment = _commentRepo.GetCommentById(id);

            try
            {
                _commentRepo.DeleteComment(id);

                return RedirectToAction("Index", new { id = databaseComment.PostId });
            }
            catch (Exception ex)
            {
                return View(comment);
            }
        }





        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

TabloidMVC/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualBasic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TabloidMVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITagRepository _tagRepository;

        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, ITagRepository tagRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _tagRepository = tagRepository;
        }

        public IActionResult Index()
        {
            List<Post> posts = _postRepository.GetAllPublishedPosts();
            List<Tag> tags = _tagRepository.GetTagsByPostId();
            PostIndexViewModel vm = new PostIndexViewModel()
            {
                Posts = posts,
                Tags = tags
            };
            
            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var post = _postRepository.GetPublishedPostById(id);

            List<Post> PostWithTags = _postRepository.GetTagByPostId(id);

            

            if (post == null)
            {
                int userId = GetCurrentUserProfileId();
                post = _postRepository.GetUserPostById(id, userId);
                if (post == null)
                {
                    return NotFound();
                }
            }
           
            PostDetailsViewModel vm = new PostDetailsViewModel()
            {
                Post = post,
                TagsByPostId = PostWithTags,
                
            };
            return View(vm);
        }

        public IActionResult Create()
        {
            var vm = new PostCreateViewModel();
            var AllTags = _tagRepository.GetAllTags();
            vm.Tags = new List<SelectListItem>();
            foreach (Tag tag in AllTags)
            {
                SelectListItem tagOption = new SelectListItem()
                {
                    Value = tag.Id.ToString(),
                    Text = tag.Name
                };
                vm.Tags.Add(tagOption);
            }

            vm.CategoryOptions = _categoryRepository.GetAll();
                       
            
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel vm)
        {
            try
            {
                vm.Post.CreateDateTime = DateAndTime.Now;
                vm.Post.IsApproved = true;
                vm.Post.UserProfileId = GetCurrentUserProfileId();
                vm.Post.DELETED = false;
                
                _postRepository.Add(vm.Post);

                foreach(var tagId in vm.SelectedTags)
                {
                    _postRepository.InsertTag(vm.Post.Id, tagId);
                }
                
                return RedirectToAction("Details", new { id = vm.Post.Id });
            } 
            catch
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        [Authorize]
        public IActionResult Edit(int id)
        {

            int currentUserId = GetCurrentUserProfileId();
            Post post = _postRepository.GetUserPostById(id, currentUserId);
            List<Category> categories = _categoryRepository.GetAll();
            List<Tag> tags = _tagRepository.GetAllTags();
            
            PostEditViewModel vm = new PostEditViewModel()
            {
                Post = post,
                CategoryOptions = categories,
                Tags = tags,
                Tag = new Tag()
            };

            if(post == null)
            {
                return NotFound();
            }

            if(post.UserProfileId == currentUserId)
            {
                return View(vm);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Post post)
        {
            try
            {
                int currentUserId = GetCurrentUserProfileId();
                Post originalPost = _postRepository.GetUserPostById(id, currentUserId);
                
                post.Id = id;
                post.CreateDateTime = originalPost.CreateDateTime;
                // Setting this to always be true for easy testing, may need to set this to false later so an admin can approve edits
                post.IsApproved = true;
                post.PublishDateTime = originalPost.PublishDateTime;
                post.UserProfileId = currentUserId;

                _postRepository.UpdatePost(post);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                List<Category> categories = _categoryRepository.GetAll();
                List<Tag> tags = _tagRepository.GetAllTags();
                PostEditViewModel vm = new PostEditViewModel()
                {
                    Post = post,
                    CategoryOptions = categories,
                    Tags = tags,
                    Tag = new Tag()
                };
                return View(vm);
            }
        }

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }



        [Authorize]
        public ActionResult Delete(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);
            int userId = GetCurrentUserId();

            if (post.UserProfileId == userId)
            {
                return View(post);
            }
            else
            {
                return NotFound();
            }
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Post post)
        {
            try
            {
                _postRepository.DeletePost(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(post);
            }
        }


        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }

       
    }
}

TabloidMVC/Views/Comments/Create.cshtml
@model TabloidMVC.Models.Comment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostId" class="control-label"></label>
                <input asp-for="PostId" class="form-control" />
                <span asp-validation-for="PostId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Comments/Delete.cshtml
@model TabloidMVC.Models.Comment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@Model.PostId">Back to List</a>
    </form>
</div>

TabloidMVC/Views/Comments/Edit.cshtml
@model TabloidMVC.Models.Comment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="PostId" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.PostId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Comments/Index.cshtml
@model TabloidMVC.Models.ViewModels.PostCommentsViewModel

@{
    ViewData["Title"] = "Index"
    ;
}


<h1 class="mb-4">@Model.Post.Title</h1>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Author
            </th>
            <th>
                Subject
            </th>
            <th>
                Content
            </th>
            <th>
                CreateDateTime
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Comments)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDateTime)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Post" asp-action="Index">Back to List</a>